name: Prmier workflow

on: push

jobs:
 hola_mundo:
  runs-on: ubuntu-lastest

  steps:
   - name: Mostrar mensaje
     run: echo "Hola Git Actions"
   - name: Bajar codigo
     uses: actions/checkout@v4
   - name: Probar codigo
     run: python3 main.py
